services:
  - type: worker       # O web, según como lo configuraras
    name: corella-multi
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
